package com.aurax.operator.core.settings

import android.content.Context
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow

/** Local type-safe v3 settings facade; values remain on-device and API-28 compatible. */
class SettingsRepository(context: Context) {
    private val prefs=context.getSharedPreferences("aura_settings_v3",Context.MODE_PRIVATE)
    private fun b(k:String,d:Boolean)=prefs.getBoolean(k,d); private fun i(k:String,d:Int)=prefs.getInt(k,d); private fun f(k:String,d:Float)=prefs.getFloat(k,d); private fun s(k:String,d:String)=prefs.getString(k,d)?:d
    private fun put(k:String,v:Any)=prefs.edit().apply{when(v){is Boolean->putBoolean(k,v);is Int->putInt(k,v);is Float->putFloat(k,v);is String->putString(k,v)}}.apply()
    var activeModelId:String get()=s("active_model_id","qwen2.5-0.5b-instruct-q4km") set(v)=put("active_model_id",v)
    var contextLength:Int get()=i("context_length",2048) set(v)=put("context_length",v.coerceIn(256,8192)); var temperature:Float get()=f("temperature",.2f) set(v)=put("temperature",v.coerceIn(0f,1.5f)); var topP:Float get()=f("top_p",.9f) set(v)=put("top_p",v.coerceIn(.1f,1f)); var topK:Int get()=i("top_k",40) set(v)=put("top_k",v.coerceIn(1,200)); var maxOutputTokens:Int get()=i("max_output_tokens",512) set(v)=put("max_output_tokens",v.coerceIn(32,4096)); var thinkingMode:String get()=s("thinking_mode","BALANCED") set(v)=put("thinking_mode",v); var cpuThreads:Int get()=i("cpu_threads",4) set(v)=put("cpu_threads",v.coerceIn(1,12)); var gpuAcceleration:Boolean get()=b("gpu_acceleration",false) set(v)=put("gpu_acceleration",v); var batchSize:Int get()=i("batch_size",512) set(v)=put("batch_size",v.coerceIn(32,2048))
    var wakeWordEnabled:Boolean get()=b("wake_word_enabled",false) set(v)=put("wake_word_enabled",v); var wakeWordSensitivity:Float get()=f("wake_word_sensitivity",.7f) set(v)=put("wake_word_sensitivity",v.coerceIn(.1f,1f)); var sttModelId:String get()=s("stt_model_id","whisper-base") set(v)=put("stt_model_id",v); var ttsVoiceId:String get()=s("tts_voice_id","default") set(v)=put("tts_voice_id",v); var ttsSpeed:Float get()=f("tts_speed",1f) set(v)=put("tts_speed",v.coerceIn(.5f,2f)); var ttsPitch:Float get()=f("tts_pitch",1f) set(v)=put("tts_pitch",v.coerceIn(.8f,1.2f)); var ttsVolume:Float get()=f("tts_volume",1f) set(v)=put("tts_volume",v.coerceIn(.1f,1f)); var autoDetectLanguage:Boolean get()=b("auto_detect_language",true) set(v)=put("auto_detect_language",v); var preferredLanguage:String get()=s("preferred_language","auto") set(v)=put("preferred_language",v); var endOfSpeechTimeout:Int get()=i("end_of_speech_timeout",2) set(v)=put("end_of_speech_timeout",v.coerceIn(1,5)); var bargeInEnabled:Boolean get()=b("barge_in_enabled",true) set(v)=put("barge_in_enabled",v)
    var automationPolicy:String get()=s("automation_policy","CONFIRM_ACTIONS") set(v)=put("automation_policy",v); var confirmationSeconds:Int get()=i("confirmation_seconds",3) set(v)=put("confirmation_seconds",v.coerceIn(1,10)); var maxActionsPerTask:Int get()=i("max_actions",30) set(v)=put("max_actions",v.coerceIn(1,200)); var maxTaskSeconds:Int get()=i("max_task_seconds",120) set(v)=put("max_task_seconds",v.coerceIn(5,900)); var screenshotVerification:Boolean get()=b("screenshot_verification",true) set(v)=put("screenshot_verification",v); var visionModelEnabled:Boolean get()=b("vision_model_enabled",false) set(v)=put("vision_model_enabled",v); var countdownEnabled:Boolean get()=b("countdown_enabled",true) set(v)=put("countdown_enabled",v); var abortOnScreenChange:Boolean get()=b("abort_on_screen_change",true) set(v)=put("abort_on_screen_change",v)
    var memoryEnabled:Boolean get()=b("memory_enabled",true) set(v)=put("memory_enabled",v); var autoExtractMemories:Boolean get()=b("auto_extract_memories",true) set(v)=put("auto_extract_memories",v); var maxMemories:Int get()=i("max_memories",5000) set(v)=put("max_memories",v.coerceIn(100,50000)); var memoryRetentionDays:Int get()=i("memory_retention_days",365) set(v)=put("memory_retention_days",v.coerceIn(1,3650)); var vectorSearchEnabled:Boolean get()=b("vector_search_enabled",true) set(v)=put("vector_search_enabled",v); var embeddingModelId:String get()=s("embedding_model_id","hash-embedding") set(v)=put("embedding_model_id",v)
    var localOnlyMode:Boolean get()=b("local_only_mode",true) set(v)=put("local_only_mode",v); var internetSearchEnabled:Boolean get()=b("internet_search_enabled",false) set(v)=put("internet_search_enabled",v); var searchProvider:String get()=s("search_provider","duckduckgo") set(v)=put("search_provider",v); var activityLogging:Boolean get()=b("activity_logging",true) set(v)=put("activity_logging",v); var safetyLogRetention:Int get()=i("safety_log_retention",90) set(v)=put("safety_log_retention",v.coerceIn(7,3650)); var biometricLock:Boolean get()=b("biometric_lock",true) set(v)=put("biometric_lock",v); var incognitoRespected:Boolean get()=b("incognito_respected",true) set(v)=put("incognito_respected",v); var passwordFilterEnabled:Boolean get()=b("password_filter",true) set(v)=put("password_filter",v)
    var theme:String get()=s("theme","SYSTEM") set(v)=put("theme",v); var dynamicColors:Boolean get()=b("dynamic_colors",false) set(v)=put("dynamic_colors",v); var animationsEnabled:Boolean get()=b("animations_enabled",true) set(v)=put("animations_enabled",v); var reducedMotion:Boolean get()=b("reduced_motion",false) set(v)=put("reduced_motion",v); var fontScale:Float get()=f("font_scale",1f) set(v)=put("font_scale",v.coerceIn(.85f,1.5f)); var glassmorphismIntensity:Float get()=f("glass_intensity",.8f) set(v)=put("glass_intensity",v.coerceIn(0f,1f)); var orbStyle:String get()=s("orb_style","CLASSIC") set(v)=put("orb_style",v)
    var performanceMode:String get()=s("performance_mode","BALANCED") set(v)=put("performance_mode",v); var batterySaverThreshold:Int get()=i("battery_threshold",20) set(v)=put("battery_threshold",v.coerceIn(5,80)); var thermalProtection:Boolean get()=b("thermal_protection",true) set(v)=put("thermal_protection",v); var backgroundTasks:Boolean get()=b("background_tasks",true) set(v)=put("background_tasks",v); var autoUnloadModel:Boolean get()=b("auto_unload_model",true) set(v)=put("auto_unload_model",v); var autoUnloadTimeout:Int get()=i("auto_unload_timeout",10) set(v)=put("auto_unload_timeout",v.coerceIn(1,120))
    var lanServerEnabled:Boolean get()=b("lan_server_enabled",false) set(v)=put("lan_server_enabled",v); var lanServerPort:Int get()=i("lan_server_port",8080) set(v)=put("lan_server_port",v.coerceIn(1024,65535)); var lanServerAuth:Boolean get()=b("lan_server_auth",true) set(v)=put("lan_server_auth",v); var remoteModelUrl:String get()=s("remote_model_url","") set(v)=put("remote_model_url",v); var debugMode:Boolean get()=b("debug_mode",false) set(v)=put("debug_mode",v); var verboseLogging:Boolean get()=b("verbose_logging",false) set(v)=put("verbose_logging",v); var showInternalStates:Boolean get()=b("show_internal_states",false) set(v)=put("show_internal_states",v); var exportDebugInfo:Boolean get()=b("export_debug_info",false) set(v)=put("export_debug_info",v)
    private val _revision=MutableStateFlow(0L); val revision:StateFlow<Long> = _revision.asStateFlow(); fun touch(){_revision.value=System.currentTimeMillis()}
}
