package com.aurax.operator.core.settings

import android.content.Context
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow

/** Type-safe settings facade backed by Preferences DataStore with legacy migration. */
class SettingsRepository(context: Context) {
    private val store = SettingsDataStoreBackend(context)
    private fun b(k: String, d: Boolean) = store.getBoolean(k, d)
    private fun i(k: String, d: Int) = store.getInt(k, d)
    private fun f(k: String, d: Float) = store.getFloat(k, d)
    private fun s(k: String, d: String) = store.getString(k, d)
    private fun pb(k: String, v: Boolean) { store.putBoolean(k, v) }
    private fun pi(k: String, v: Int) { store.putInt(k, v) }
    private fun pf(k: String, v: Float) { store.putFloat(k, v) }
    private fun ps(k: String, v: String) { store.putString(k, v) }

    var activeModelId: String get() = s("active_model_id", "qwen2.5-0.5b-instruct-q4km") ; set(v) = ps("active_model_id", v)
    var contextLength: Int get() = i("context_length", 2048).coerceIn(256,4096) ; set(v) = pi("context_length", v.coerceIn(256,4096))
    var temperature: Float get() = f("temperature", .2f).coerceIn(0f,1.5f) ; set(v) = pf("temperature",v.coerceIn(0f,1.5f))
    var topP: Float get() = f("top_p",.9f).coerceIn(.1f,1f) ; set(v) = pf("top_p",v.coerceIn(.1f,1f))
    var topK: Int get() = i("top_k",40).coerceIn(1,200) ; set(v) = pi("top_k",v.coerceIn(1,200))
    var maxOutputTokens: Int get() = i("max_output_tokens",512).coerceIn(32,4096) ; set(v) = pi("max_output_tokens",v.coerceIn(32,4096))
    var thinkingMode: String get() = s("thinking_mode","BALANCED") ; set(v) = ps("thinking_mode",v)
    var cpuThreads: Int get() = i("cpu_threads",4).coerceIn(1,12) ; set(v) = pi("cpu_threads",v.coerceIn(1,12))
    var gpuAcceleration: Boolean get() = b("gpu_acceleration",false) ; set(v) = pb("gpu_acceleration",v)
    var batchSize: Int get() = i("batch_size",512).coerceIn(32,2048) ; set(v) = pi("batch_size",v.coerceIn(32,2048))
    var wakeWordEnabled: Boolean get() = b("wake_word_enabled",false) ; set(v) = pb("wake_word_enabled",v)
    var wakeWordSensitivity: Float get() = f("wake_word_sensitivity",.7f).coerceIn(.1f,1f) ; set(v) = pf("wake_word_sensitivity",v.coerceIn(.1f,1f))
    var continuousConversationEnabled: Boolean get() = b("continuous_conversation_enabled",false) ; set(v) = pb("continuous_conversation_enabled",v)
    var conversationIdleTimeout: Int get() = i("conversation_idle_timeout",30).coerceIn(5,300) ; set(v) = pi("conversation_idle_timeout",v.coerceIn(5,300))
    var sttModelId: String get() = s("stt_model_id","whisper-base") ; set(v) = ps("stt_model_id",v)
    var ttsVoiceId: String get() = s("tts_voice_id","default") ; set(v) = ps("tts_voice_id",v)
    var ttsSpeed: Float get() = f("tts_speed",1f).coerceIn(.5f,2f) ; set(v) = pf("tts_speed",v.coerceIn(.5f,2f))
    var ttsPitch: Float get() = f("tts_pitch",1f).coerceIn(.8f,1.2f) ; set(v) = pf("tts_pitch",v.coerceIn(.8f,1.2f))
    var ttsVolume: Float get() = f("tts_volume",1f).coerceIn(.1f,1f) ; set(v) = pf("tts_volume",v.coerceIn(.1f,1f))
    var autoDetectLanguage: Boolean get() = b("auto_detect_language",true) ; set(v) = pb("auto_detect_language",v)
    var preferredLanguage: String get() = s("preferred_language","auto") ; set(v) = ps("preferred_language",v)
    var endOfSpeechTimeout: Int get() = i("end_of_speech_timeout",2).coerceIn(1,5) ; set(v) = pi("end_of_speech_timeout",v.coerceIn(1,5))
    var bargeInEnabled: Boolean get() = b("barge_in_enabled",true) ; set(v) = pb("barge_in_enabled",v)
    var automationPolicy: String get() = s("automation_policy","CONFIRM_ACTIONS") ; set(v) = ps("automation_policy",v)
    var confirmationSeconds: Int get() = i("confirmation_seconds",3).coerceIn(1,10) ; set(v) = pi("confirmation_seconds",v.coerceIn(1,10))
    var maxActionsPerTask: Int get() = i("max_actions",30).coerceIn(1,200) ; set(v) = pi("max_actions",v.coerceIn(1,200))
    var maxTaskSeconds: Int get() = i("max_task_seconds",120).coerceIn(5,900) ; set(v) = pi("max_task_seconds",v.coerceIn(5,900))
    var screenshotVerification: Boolean get() = b("screenshot_verification",true) ; set(v) = pb("screenshot_verification",v)
    var visionModelEnabled: Boolean get() = b("vision_model_enabled",false) ; set(v) = pb("vision_model_enabled",v)
    var visionModelId: String get() = s("vision_model_id","") ; set(v) = ps("vision_model_id",v)
    var countdownEnabled: Boolean get() = b("countdown_enabled",true) ; set(v) = pb("countdown_enabled",v)
    var abortOnScreenChange: Boolean get() = b("abort_on_screen_change",true) ; set(v) = pb("abort_on_screen_change",v)
    var memoryEnabled: Boolean get() = b("memory_enabled",true) ; set(v) = pb("memory_enabled",v)
    var autoExtractMemories: Boolean get() = b("auto_extract_memories",true) ; set(v) = pb("auto_extract_memories",v)
    var maxMemories: Int get() = i("max_memories",5000).coerceIn(100,50000) ; set(v) = pi("max_memories",v.coerceIn(100,50000))
    var memoryRetentionDays: Int get() = i("memory_retention_days",365).coerceIn(1,3650) ; set(v) = pi("memory_retention_days",v.coerceIn(1,3650))
    var vectorSearchEnabled: Boolean get() = b("vector_search_enabled",true) ; set(v) = pb("vector_search_enabled",v)
    var ragEnabled: Boolean get() = b("rag_enabled",true) ; set(v) = pb("rag_enabled",v)
    var ragTopK: Int get() = i("rag_top_k",5).coerceIn(1,20) ; set(v) = pi("rag_top_k",v.coerceIn(1,20))
    var embeddingModelId: String get() = s("embedding_model_id","hash-embedding") ; set(v) = ps("embedding_model_id",v)
    var localOnlyMode: Boolean get() = b("local_only_mode",true) ; set(v) = pb("local_only_mode",v)
    var internetSearchEnabled: Boolean get() = b("internet_search_enabled",false) ; set(v) = pb("internet_search_enabled",v)
    var searchProvider: String get() = s("search_provider","duckduckgo") ; set(v) = ps("search_provider",v)
    var activityLogging: Boolean get() = b("activity_logging",true) ; set(v) = pb("activity_logging",v)
    var safetyLogRetention: Int get() = i("safety_log_retention",90).coerceIn(7,3650) ; set(v) = pi("safety_log_retention",v.coerceIn(7,3650))
    var biometricLock: Boolean get() = b("biometric_lock",true) ; set(v) = pb("biometric_lock",v)
    var incognitoRespected: Boolean get() = b("incognito_respected",true) ; set(v) = pb("incognito_respected",v)
    var passwordFilterEnabled: Boolean get() = b("password_filter",true) ; set(v) = pb("password_filter",v)
    var theme: String get() = s("theme","SYSTEM") ; set(v) = ps("theme",v)
    var dynamicColors: Boolean get() = b("dynamic_colors",false) ; set(v) = pb("dynamic_colors",v)
    var animationsEnabled: Boolean get() = b("animations_enabled",true) ; set(v) = pb("animations_enabled",v)
    var reducedMotion: Boolean get() = b("reduced_motion",false) ; set(v) = pb("reduced_motion",v)
    var fontScale: Float get() = f("font_scale",1f).coerceIn(.85f,1.5f) ; set(v) = pf("font_scale",v.coerceIn(.85f,1.5f))
    var glassmorphismIntensity: Float get() = f("glass_intensity",.8f).coerceIn(0f,1f) ; set(v) = pf("glass_intensity",v.coerceIn(0f,1f))
    var orbStyle: String get() = s("orb_style","CLASSIC") ; set(v) = ps("orb_style",v)
    var performanceMode: String get() = s("performance_mode","BALANCED") ; set(v) = ps("performance_mode",v)
    var batterySaverThreshold: Int get() = i("battery_threshold",20).coerceIn(5,80) ; set(v) = pi("battery_threshold",v.coerceIn(5,80))
    var thermalProtection: Boolean get() = b("thermal_protection",true) ; set(v) = pb("thermal_protection",v)
    var backgroundTasks: Boolean get() = b("background_tasks",true) ; set(v) = pb("background_tasks",v)
    var autoUnloadModel: Boolean get() = b("auto_unload_model",true) ; set(v) = pb("auto_unload_model",v)
    var autoUnloadTimeout: Int get() = i("auto_unload_timeout",10).coerceIn(1,120) ; set(v) = pi("auto_unload_timeout",v.coerceIn(1,120))
    var lanServerEnabled: Boolean get() = b("lan_server_enabled",false) ; set(v) = pb("lan_server_enabled",v)
    var lanServerPort: Int get() = i("lan_server_port",8080).coerceIn(1024,65535) ; set(v) = pi("lan_server_port",v.coerceIn(1024,65535))
    var lanServerAuth: Boolean get() = b("lan_server_auth",true) ; set(v) = pb("lan_server_auth",v)
    var remoteModelUrl: String get() = s("remote_model_url","") ; set(v) = ps("remote_model_url",v)
    var pluginExecutionEnabled: Boolean get() = b("plugin_execution_enabled",false) ; set(v) = pb("plugin_execution_enabled",v)
    var developerMode: Boolean get() = b("developer_mode",false) ; set(v) = pb("developer_mode",v)
    var debugMode: Boolean get() = b("debug_mode",false) ; set(v) = pb("debug_mode",v)
    var verboseLogging: Boolean get() = b("verbose_logging",false) ; set(v) = pb("verbose_logging",v)
    var showInternalStates: Boolean get() = b("show_internal_states",false) ; set(v) = pb("show_internal_states",v)
    var exportDebugInfo: Boolean get() = b("export_debug_info",false) ; set(v) = pb("export_debug_info",v)

    private val _revision = MutableStateFlow(0L)
    val revision: StateFlow<Long> = _revision.asStateFlow()
    fun touch() { _revision.value = System.currentTimeMillis() }
}
